//
//  CityCatalog.swift
//  ebiketrader
//

import Foundation

/// Mirrors US_STATES in the website's ListingForm.tsx — the same 51 entries
/// in the same order, so both forms offer identical choices and the stored
/// `state` value means the same thing either way.
let usStates = [
    "AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DE", "FL", "GA", "HI", "ID",
    "IL", "IN", "IA", "KS", "KY", "LA", "ME", "MD", "MA", "MI", "MN", "MS",
    "MO", "MT", "NE", "NV", "NH", "NJ", "NM", "NY", "NC", "ND", "OH", "OK",
    "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV",
    "WI", "WY", "DC",
]

/// US city names per state, for the city suggestions on the post form.
///
/// Bundled rather than fetched: the whole country is ~200KB, so shipping it
/// buys instant suggestions with no network round-trip on the first
/// keystroke. The data comes from the website's public/data/cities/*.json
/// (generated by its scripts/generate-city-data.js from GeoNames, US cities
/// with population >= 1000) flattened into one file keyed by state. To
/// refresh it, re-run that script and rebuild Resources/cities.json.
///
/// Licensing: the place names originate from GeoNames (geonames.org) and are
/// CC BY 4.0, which requires attribution — see the Credits row in
/// AccountView and the Credits section of ebiketrader.net/support. The
/// all-the-cities package that repackages them is MIT.
///
/// The point of all this, as on the web, is to steer sellers toward a
/// spelling that will actually geocode — the onListingWrite Cloud Function
/// turns city/state into the coordinates behind the map. A city that isn't
/// listed can still be typed by hand.
enum CityCatalog {
    private static let byState: [String: [String]] = {
        guard
            let url = Bundle.main.url(forResource: "cities", withExtension: "json"),
            let data = try? Data(contentsOf: url),
            let decoded = try? JSONDecoder().decode([String: [String]].self, from: data)
        else {
            // Suggestions simply don't appear; typing a city by hand still works.
            return [:]
        }
        return decoded
    }()

    static func cities(in state: String) -> [String] {
        byState[state.uppercased()] ?? []
    }

    static func isKnown(_ city: String, in state: String) -> Bool {
        let target = city.trimmingCharacters(in: .whitespaces)
        guard !target.isEmpty else { return false }
        return cities(in: state).contains { $0.caseInsensitiveCompare(target) == .orderedSame }
    }

    /// Up to `limit` matches for `query` within `state`.
    ///
    /// Names arrive most-populous-first and that order is kept, but names
    /// that *start* with the query come ahead of ones that merely contain it.
    /// The website's <datalist> leaves ranking to the browser, which is why
    /// typing "s" there offers Los Angeles — technically a match, rarely what
    /// you meant.
    static func suggestions(for query: String, in state: String, limit: Int = 8) -> [String] {
        let needle = query.trimmingCharacters(in: .whitespaces)
        guard !needle.isEmpty, !state.isEmpty else { return [] }

        var startsWith: [String] = []
        var contains: [String] = []

        for name in cities(in: state) {
            if name.lowercased().hasPrefix(needle.lowercased()) {
                startsWith.append(name)
                if startsWith.count >= limit { break }
            } else if contains.count < limit, name.localizedCaseInsensitiveContains(needle) {
                contains.append(name)
            }
        }

        return Array((startsWith + contains).prefix(limit))
    }
}
